# Generated by Django 4.2.9 on 2024-01-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
