# Generated by Django 4.2.9 on 2024-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_1',
            new_name='author_id',
        ),
    ]
