# Generated by Django 4.2.9 on 2024-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_showtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
